// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4YyvpV_NiVoGLxaLb5HhlIMhWDVUWyN0',
    appId: '1:306779608954:web:f7f0169645260dd3c428c3',
    messagingSenderId: '306779608954',
    projectId: 'eventos-uesb',
    authDomain: 'eventos-uesb.firebaseapp.com',
    storageBucket: 'eventos-uesb.appspot.com',
    measurementId: 'G-7D810BXKRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfSPWOH1OZOu9a0qaeOB9i_lCPd91dZtU',
    appId: '1:306779608954:android:bf78a60f5a20880cc428c3',
    messagingSenderId: '306779608954',
    projectId: 'eventos-uesb',
    storageBucket: 'eventos-uesb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYcCcJrvfIe491bXNtE9F4BupvoW8nFg8',
    appId: '1:306779608954:ios:ff774e5d83db9f19c428c3',
    messagingSenderId: '306779608954',
    projectId: 'eventos-uesb',
    storageBucket: 'eventos-uesb.appspot.com',
    iosClientId: '306779608954-oc4sj0uo1je69a1hc6olng7pt5fbt7n8.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventosUesb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYcCcJrvfIe491bXNtE9F4BupvoW8nFg8',
    appId: '1:306779608954:ios:ff774e5d83db9f19c428c3',
    messagingSenderId: '306779608954',
    projectId: 'eventos-uesb',
    storageBucket: 'eventos-uesb.appspot.com',
    iosClientId: '306779608954-oc4sj0uo1je69a1hc6olng7pt5fbt7n8.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventosUesb',
  );
}
